### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by EdwardLuke** [fermion-star/apple_sensors#1]
Would it be possible to get some additional instructions on how to compile this project?

`gcc temp_sensor.m` produces a list of undefined symbols, which I'm guessing means I'm missing a compile-time dependency.

If it isn't obvious, I'm completely new to Objective-C/C++. Thanks!

**Comment by lsman333** [comment]
+1

**Comment by fermion-star** [comment]
You may use Xcode to compile it. 
1. create a new project of macOS command line tool, and specify its language to be Objective-C
2. replace the content of default `main.m` with `temp_sensor.m`.
3. compile and get the binary.

**Comment by EdwardLuke** [comment]
That's a great help, thanks!

**Comment by fermion-star** [comment]
`clang temp_sensor.m -framework IOKit -framework Foundation -o temp_sensor` also works.
